apiVersion: apps/v1
kind: Deployment
metadata:
  name: student2-deployment
  namespace: student2
spec:
  selector:
    matchLabels:
      app: student2
  template:
    metadata:
      labels:
        app: student2
    spec:
      containers:
      - name: student2
        image: registry.tanzu.dk/ops2devops/student2:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student2
spec:
  type: NodePort
  selector:
    app: student2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30012 # R##emember to change to student number.

